<?php
$arr = array(
    'assets_button' => __('OptimizePress: Add Element', 'optimizepress'),

    'slide_2_title' => __('Choose the %element_name% Style', 'optimizepress'),
    'slide_3_title' => __('Step 3 - %element_name%', 'optimizepress'),
    'slide_4_title' => __('Step 4 - %element_name%', 'optimizepress'),

    'help_video' => __('Help Video', 'optimizepress'),

    //generic
    'add_new' => __('Add New', 'optimizepress'),
    'add_new_field' => __('Add New Field', 'optimizepress'),
    'add_new_row' => __('Add New Row', 'optimizepress'),
    'advanced_options' => __('Advanced Options', 'optimizepress'),
    'next_step' => __('Next Step', 'optimizepress'),
    'after' => __('After', 'optimizepress'),
    'alert_text' => __('Alert Message', 'optimizepress'),
    'alignment' => __('Alignment', 'optimizepress'),
    'alt_text' => __('Alt Text', 'optimizepress'),
    'before' => __('Before', 'optimizepress'),
    'bg_img' => __('Background Image', 'optimizepress'),
    'bg_color' => __('Background Colour', 'optimizepress'),
    'bg_color_start' => __('Background Gradient Start Colour', 'optimizepress'),
    'bg_color_end' => __('Background Gradient End Colour (If left blank, color will be solid)', 'optimizepress'),
    'border_style' => __('Border Style', 'optimizepress'),
    'button_text' => __('Button Text', 'optimizepress'),
    'center' => __('Center', 'optimizepress'),
    'caption' => __('Caption', 'optimizepress'),
    'color' => __('Colour', 'optimizepress'),
    'columns' => __('Columns', 'optimizepress'),
    'columns_count' => __('Number Of Columns', 'optimizepress'),
    'company' => __('Company', 'optimizepress'),
    'content' => __('Content', 'optimizepress'),
    'dark' => __('Dark', 'optimizepress'),
    'delete' => __('Delete', 'optimizepress'),
    'dimensions' => __('Dimensions', 'optimizepress'),
    'edit_element' => __('Edit Element', 'optimizepress'),
    'edit_parent_element' => __('Edit Parent Element', 'optimizepress'),
    'email_address' => __('Email Address', 'optimizepress'),
    'feature_title' => __('Feature Title', 'optimizepress'),
    'feature_description' => __('Feature Description', 'optimizepress'),
    'font_settings' => __('Custom Font Settings', 'optimizepress'),
    'form_html' => __('Form HTML', 'optimizepress'),
    'full_width' => __('Full Width', 'optimizepress'),
    'GET' => __('GET', 'optimizepress'),
    'header' => __('Header', 'optimizepress'),
    'headline' => __('Headline', 'optimizepress'),
    'headline_tag' => __('Headline Tag', 'optimizepress'),
    'height' => __('Height (px)', 'optimizepress'),
    'highlight' => __('Highlight', 'optimizepress'),
    'icon' => __('Icon (click on image to see all available icons)', 'optimizepress'),
    'image' => __('Image', 'optimizepress'),
    'information' => __('Information', 'optimizepress'),
    'Insert' => __('Insert', 'optimizepress'),
    'language' => __('Language', 'optimizepress'),
    'large' => __('Large', 'optimizepress'),
    'large_icon' => __('Large Icon', 'optimizepress'),
    'large_image' => __('Large Image', 'optimizepress'),
    'left' => __('Left', 'optimizepress'),
    'letter_spacing' => __('Letter Spacing', 'optimizepress'),
    'light' => __('Light', 'optimizepress'),
    'like' => __('Like', 'optimizepress'),
    'line_height' => __('Line Height', 'optimizepress'),
    'link_title' => __('Link Title', 'optimizepress'),
    'link_title_default' => __('Click here for popup', 'optimizepress'),
    'link_url' => __('Link URL', 'optimizepress'),
    'linkedin_language' => __('LinkedIn Language', 'optimizepress'),
    'linkedin_url' => __('LinkedIn URL', 'optimizepress'),
    'list_items' => __('List Items', 'optimizepress'),
    'margin_top' => __('Top Margin (px)', 'optimizepress'),
    'margin_bottom' => __('Bottom Margin (px)', 'optimizepress'),
    'margin_left' => __('Left Margin (px)', 'optimizepress'),
    'margin_right' => __('Right Margin (px)', 'optimizepress'),
    'medium' => __('Medium', 'optimizepress'),
    'most_popular' => __('Most Popular', 'optimizepress'),
    'most_popular_text' => __('Most Popular Text', 'optimizepress'),
    'move' => __('Move', 'optimizepress'),
    'normal' => __('Normal', 'optimizepress'),
    'slow' => __('Slow', 'optimizepress'),
    'fast' => __('Fast', 'optimizepress'),
    'none' => __('None', 'optimizepress'),
    'fade' => __('Fade', 'optimizepress'),
    'elastic' => __('Elastic', 'optimizepress'),
    'zoomIn' => __('Zoom In', 'optimizepress'),
    'zoomOut' => __('Zoom Out', 'optimizepress'),
    'order_button_text' => __('Order Button Text', 'optimizepress'),
    'order_button_url' => __('Order Button URL', 'optimizepress'),
    'package_description' => __('Package Description', 'optimizepress'),
    'package_features' => __('Package Features', 'optimizepress'),
    'percentage' => __('Percentage', 'optimizepress'),
    'placeholder' => __('Placeholder', 'optimizepress'),
    'placeholder_image' => __('Placeholder Image', 'optimizepress'),
    'placeholder_width' => __('Placeholder Width', 'optimizepress'),
    'placeholder_height' => __('Placeholder Height', 'optimizepress'),
    'POST' => __('POST', 'optimizepress'),
    'posts_title' => __('Posts Title', 'optimizepress'),
    'posts_rows' => __('Number Of Posts Per Row', 'optimizepress'),
    'posts_num' => __('Number Of Posts', 'optimizepress'),
    'posts_text_excerpt' => __('Show First 100 Characters?', 'optimizepress'),
    'posts_multiselect' => __('Posts selection', 'optimizepress'),
    'posts_mode' => __('Posts mode selection', 'optimizepress'),
    'posts_hide_author' => __('Hide author info and categories tags?', 'optimizepress'),
    'posts_main_title_font_settings' => __('Main Element Title Font Settings', 'optimizepress'),
    'post_title_font_settings' => __('Post Title Font Settings', 'optimizepress'),
    'post_description_font_settings' => __('First 100 Characters Font Settings', 'optimizepress'),
    'progress_text_shown' => __('Text Shown Next to Progress Percentage', 'optimizepress'),
    'price' => __('Price', 'optimizepress'),
    'pricing_unit' => __('Pricing Unit', 'optimizepress'),
    'pricing_variable' => __('Pricing Variable', 'optimizepress'),
    'privacy_notice' => __('Privacy Notice', 'optimizepress'),
    'recommend' => __('Recommend', 'optimizepress'),
    'remove_file' => __('Remove File', 'optimizepress'),
    'remove_image' => __('Remove Image', 'optimizepress'),
    'remove_row' => __('Remove Row', 'optimizepress'),
    'reset' => __('Reset', 'optimizepress'),
    'right' => __('Right', 'optimizepress'),
    'rounded' => __('Rounded', 'optimizepress'),
    'size' => __('Size', 'optimizepress'),
    'small' => __('Small', 'optimizepress'),
    'small_icon' => __('Small Icon', 'optimizepress'),
    'step' => __('Step', 'optimizepress'),
    'steps' => __('Steps', 'optimizepress'),
    'style' => __('Style', 'optimizepress'),
    'submit_button' => __('Submit Button', 'optimizepress'),
    'text' => __('Text', 'optimizepress'),
    'timer' => __('Timer (milliseconds)', 'optimizepress'),
    'title' => __('Title', 'optimizepress'),
    'Top' => __('Top', 'optimizepress'),
    'type' => __('Type', 'optimizepress'),
    'view_file' => __('View File', 'optimizepress'),
    'video_type' => __('Video Type', 'optimizepress'),
    'width' => __('Width (px)', 'optimizepress'),
    'only_advanced_fields_available_when_editing' => __('There are no title options for the choosen style', 'optimizepress'),
    'order' => __('Order', 'optimizepress'),
    'required' => __('Required', 'optimizepress'),
    'hidden' => __('Hidden', 'optimizepress'),
    'email_order' => __('Email field order', 'optimizepress'),
    'name_order' => __('Name field order', 'optimizepress'),
    'name_required' => __('Name required', 'optimizepress'),
    'page_overwritten_continue' => __('Your page will be overwritten. Are you sure you want to continue?', 'optimizepress'),

    'top_margin' => __('Top Margin (px)', 'optimizepress'),
    'bottom_margin' => __('Bottom Margin (px)', 'optimizepress'),
    'left_margin' => __('Left Margin (px)', 'optimizepress'),
    'right_margin' => __('Right Margin (px)', 'optimizepress'),

    'top_padding' => __('Top Padding (px)', 'optimizepress'),
    'bottom_padding' => __('Bottom Padding (px)', 'optimizepress'),
    'left_padding' => __('Left Padding (px)', 'optimizepress'),
    'right_padding' => __('Right Padding (px)', 'optimizepress'),

    'saved' => __('Saved', 'optimizepress'),

    //colors
    'black' => __('Black', 'optimizepress'),
    'blue' => __('Blue', 'optimizepress'),
    'bright_green' => __('Bright Green', 'optimizepress'),
    'dark_blue' => __('Dark Blue', 'optimizepress'),
    'dark_grey' => __('Dark Grey', 'optimizepress'),
    'dark_orange' => __('Dark Orange', 'optimizepress'),
    'green' => __('Green', 'optimizepress'),
    'light_blue' => __('Light Blue', 'optimizepress'),
    'light_green' => __('Light Green', 'optimizepress'),
    'light_orange' => __('Light Orange', 'optimizepress'),
    'light_red' => __('Light Red', 'optimizepress'),
    'light_violet' => __('Light Violet', 'optimizepress'),
    'orange' => __('Orange', 'optimizepress'),
    'pink' => __('Pink', 'optimizepress'),
    'red' => __('Red', 'optimizepress'),
    'silver' => __('Silver', 'optimizepress'),
    'teal' => __('Teal', 'optimizepress'),
    'violet' => __('Violet', 'optimizepress'),
    'yellow' => __('Yellow', 'optimizepress'),

    //tag specific
    //Affiliate Page Asset
    'affiliate_link' => __('Affiliate Link', 'optimizepress'),

    //Bullet Block Asset
    'bullet_block_advanced1' => __('Customize specific styling options for your bullets.', 'optimizepress'),
    'bullet_font_settings' => __('Bullet Styling', 'optimizepress'),
    'bullet_upload_icon' => __('Upload bullet block icon (if custom icon is uploaded, the above icon will be ignored.)', 'optimizepress'),

    //Content Toggle Asset
    'content_toggle_label' => __('Show Text', 'optimizepress'),
    'content_toggle_hide_label' => __('Hide Text', 'optimizepress'),
    'content_toggle_advanced1' => __('Customize specific styling options for your content toggle text', 'optimizepress'),
    'content_toggle_font_settings' => __('Main Content Styling', 'optimizepress'),

    //Calendar Date and Time Asset
    'calendar_bar_color' => __('Month Background Color', 'optimizepress'),
    'day' => __('Day', 'optimizepress'),
    'full_date' => __('Full Date', 'optimizepress'),
    'month' => __('Month', 'optimizepress'),
    'time_1' => __('Time 1', 'optimizepress'),
    'time_2' => __('Time 2', 'optimizepress'),
    'time_3' => __('Time 3', 'optimizepress'),
    'timezone_1' => __('Timezone 1', 'optimizepress'),
    'timezone_2' => __('Timezone 2', 'optimizepress'),
    'timezone_3' => __('Timezone 3', 'optimizepress'),

    //Countdown Cookie Timer Asset
    'countdown_cookie_timer_instructions' => __('Choose a length of time to count down to', 'optimizepress'),
    'length_of_time' => __('Length of Time', 'optimizepress'),
    'length_of_time_suffix' => __('Length of Time Suffix', 'optimizepress'),

    //Countdown Timer Asset
    'countdown_timer_instructions' => __('Please enter the date in GMT time format. You can learn more about converting the time at http://www.greenwichmeantime.com.', 'optimizepress'),
    'countdown_timer_advanced_instructions' => __('Use the below form to change the text that is associated with the years, months, days, hours, minutes and seconds on your countdown timer.', 'optimizepress'),
    'years_text' => __('Years Text (Plural)', 'optimizepress'),
    'years_text_singular' => __('Years Text (Singular)', 'optimizepress'),
    'months_text' => __('Months Text {Plural)', 'optimizepress'),
    'months_text_singular' => __('Months Text {Singular)', 'optimizepress'),
    'days_text' => __('Days Text (Plural)', 'optimizepress'),
    'days_text_singular' => __('Days Text (Singular)', 'optimizepress'),
    'hours_text' => __('Hours Text (Plural)', 'optimizepress'),
    'hours_text_singular' => __('Hours Text (Singular)', 'optimizepress'),
    'minutes_text' => __('Minutes Text (Plural)', 'optimizepress'),
    'minutes_text_singular' => __('Minutes Text (Singular)', 'optimizepress'),
    'seconds_text' => __('Seconds Text (Plural)', 'optimizepress'),
    'seconds_text_singular' => __('Seconds Text (Singular)', 'optimizepress'),

    //Course Description Asset
    'course_description_step_2' => __('You may choose either an icon from the list below or upload one of your own', 'optimizepress'),
    'course_description_title' => __('Training/Course Title', 'optimizepress'),
    'course_description_content' => __('Training/Course Description', 'optimizepress'),
    'course_description_advanced1' => __('Customize specific styling options for your course description text', 'optimizepress'),
    'course_description_title_styling' => __('Course Description Title Styling', 'optimizepress'),
    'course_description_content_styling' => __('Course Description Content Styling', 'optimizepress'),

    //Feature Block Asset
    'feature_block_advanced1' => __('Customize specific styling options for your feature block text', 'optimizepress'),
    'feature_block_title_styling' => __('Feature Block Title Styling', 'optimizepress'),
    'feature_block_content_styling' => __('Feature Block Content Styling', 'optimizepress'),
    'feature_block_link' => __('Link (if you use this option links from content area above will not be displayed)', 'optimizepress'),
    'feature_upload_icon' => __('Upload featue block icon (if custom icon is uploaded, the above icon will be ignored.', 'optimizepress'),

    //Feature Box Asset
    'feature_box_advanced1' => __('Customize specific styling options for your feature box text', 'optimizepress'),
    'feature_box_title_styling' => __('Feature Box Title Styling', 'optimizepress'),
    'feature_box_content_styling' => __('Feature Box Content Styling', 'optimizepress'),
    'feature_text' => __('Feature Text', 'optimizepress'),

    //Guarantee Box Asset
    'guarantee_box_advanced1' => __('Customize specific styling options for your guarantee box', 'optimizepress'),
    'guarantee_box_title_styling' => __('Guarantee Box Title Styling', 'optimizepress'),
    'guarantee_box_content_styling' => __('Guarantee Box Content Styling', 'optimizepress'),

    'credit_card_icons' => __('Credit Card Icons', 'optimizepress'),

    'divider_top_text' => __('Top Link Text', 'optimizepress'),

    'tabs_count' => __('Number of tabs', 'optimizepress'),
    'tabs' => __('Tabs', 'optimizepress'),
    'tab' => __('Tab', 'optimizepress'),

    'embed' => __('Embed Code', 'optimizepress'),
    'video_embed_microcopy' => __('If you need to embed Wistia or EVS code, please use Custom HTML/Shortcode element and paste embed code there. Unfortunately EVS embed code is not compatible with our OverlayOptimizer element.', 'optimizepress'),
    'URL' => __('URL', 'optimizepress'),
    'hide_controls' => __('Hide Controls', 'optimizepress'),
    'auto_play' => __('Auto Play', 'optimizepress'),
    'auto_buffer' => __('Auto Buffering', 'optimizepress'),
    'auto_buffer_help' => __('Enabling auto buffering will allow the video to be loaded before the user clicks play', 'optimizepress'),
    'remove_youtube_logo' => __('Hide YouTube logo in control bar (will still show in corner of video on hover)', 'optimizepress'),
    'show_title_bar' => __('Show title bar', 'optimizepress'),
    'force_hd_mode' => __('Force HD mode', 'optimizepress'),

    'title_alt' => __('Title Alt Attribute', 'optimizepress'),
    'header_alt' => __('Header Alt Attribute', 'optimizepress'),

    'tour_get_started_link' => __('Get Started URL', 'optimizepress'),
    'tour_get_started_text' => __('Get Started Text', 'optimizepress'),
    'tour_tour_link' => __('Tour Link URL', 'optimizepress'),
    'tour_tour_text' => __('Tour Link Text', 'optimizepress'),
    'tour_headline' => __('Headline', 'optimizepress'),
    'tour_subheadline' => __('Sub Headline', 'optimizepress'),

    'qna_questions' => __('Questions', 'optimizepress'),
    'qna_question' => __('Question', 'optimizepress'),
    'qna_answer' => __('Answer', 'optimizepress'),
    'qna_qa_text' => __('Q &amp; A Text', 'optimizepress'),
    'qna_large_q' => __('Large Q', 'optimizepress'),


    'email_default' => __('Email Default Value', 'optimizepress'),
    'name_default' => __('Name Default Value', 'optimizepress'),
    'name' => __('Name', 'optimizepress'),
    'email' => __('Email', 'optimizepress'),
    'email_data' => __('Email Data', 'optimizepress'),
    'new_window' => __('Open In New Window', 'optimizepress'),
    'disable_name' => __('Disable Name', 'optimizepress'),
    'method' => __('Method', 'optimizepress'),
    'form_url' => __('Form URL', 'optimizepress'),
    'redirect_url' => __('Redirect URL', 'optimizepress'),
    'redirect_url_instructions' => __('Enter a URL in the Redirect URL field below if you wish to redirect your visitors when your timer reaches 0. Leave this field empty if you do not wish to redirect.', 'optimizepress'),
    'field_name' => __('Field Name', 'optimizepress'),
    'extra_fields' => __('Extra Fields', 'optimizepress'),
    'value' => __('Value', 'optimizepress'),


    'order_selected_step' => __('Selected Step', 'optimizepress'),
    'order_step1_text' => __('Step 1 Text', 'optimizepress'),
    'order_step1_href' => __('Step 1 Link URL', 'optimizepress'),
    'order_step2_text' => __('Step 2 Text', 'optimizepress'),
    'order_step2_href' => __('Step 2 Link URL', 'optimizepress'),
    'order_step3_text' => __('Step 3 Text', 'optimizepress'),

    'testimonial' => __('Testimonial', 'optimizepress'),

    'width_help_add_suffix' => __('Please enter your width including your measurement unit e.g. \'px\' or \'%\'', 'optimizepress'),

    'facebook_hide_like' => __('Hide Like button', 'optimizepress'),
    'facebook_hide_like_help' => __('Hide the Facebook Like button above the comments', 'optimizepress'),
    'facebook_language_help' => __('Set the language for your Facebook comments system here', 'optimizepress'),
    'facebook_posts_number' => __('Number of posts to show', 'optimizepress'),
    'facebook_posts_number_help' => __('Enter the number of Facebook comments to show by default_attr(we recommend 10)', 'optimizepress'),
    'facebook_src_url' => __('Facebook Comments Source URL', 'optimizepress'),
    'facebook_src_url_help' => __('If you would like to associate all your comments with a particular page on your site, or show the same comments on multiple pages (perhaps for a launch) enter the URL here. We recommend using your root domain URL.', 'optimizepress'),
    'facebook_posts_order' => __('The order to use when displaying comments'),
    'facebook_posts_order_help' => __('<strong>Social Relevance</strong>: The Comments plugin uses social signals to surface the highest quality comments. Comments are ordered to display the most relevant comments from friends and friends of friends as well as the most-liked or active discussion threads.<br /><br />
        <strong>Newest</strong>: Comments are shown in the opposite order from which they were posted, with the newest comments at the top, and the oldest at the bottom.<br /><br />
        <strong>Oldest</strong>: Comments are shown in the order in which they were posted, with the oldest comments at the top, and the newest at the bottom.
        '),

    'advanced_warning_2' => __('Warning: These options are for advanced users only.  Customizing these options can result in your elements looking distorted or your design breaking.  If in doubt, leave these options on their default settings.', 'optimizepress'),

    'image_alignment' => __('Image Alignment', 'optimizepress'),

    'main_text' => __('Main Text', 'optimizepress'),

    'navigation_font_settings' => __('Navigation Content Styling', 'optimizepress'),
    'navigation_advanced1' => __('Customize specific styling options for your navigation menu.', 'optimizepress'),

    'order_box_advanced1' => __('Customize specific styling options for your order box', 'optimizepress'),
    'width_needed_for_alignment_to_work' => __('For alignment to work you need to define width', 'optimizepress'),

    'autoresponder_name' => __('Autoresponder Name', 'optimizepress'),

    'opm_integration' => __('OptimizeMember Integration', 'optimizepress'),
    'opm_integration_copy_1' => __('If you want to add a subscriber as a user inside your OptimizeMember membership, select the relevant level and any packages to apply below. Note that no payment will be taken and this user will be added directly to the level/packages you specify.', 'optimizepress'),
    'opm_integration_copy_2' => __('We recommend collecting name and email on your form when using this option to ensure your user is created with the correct details.', 'optimizepress'),

    'optin_box_advanced1' => __('Customize specific styling options for your optin box text', 'optimizepress'),
    'optin_box_font_settings' => __('Optin Box Font Styling', 'optimizepress'),

    'tabs_font_settings' => __('Tab Content Styling', 'optimizepress'),
    'tabs_advanced1' => __('Customize specific styling options for your tab content', 'optimizepress'),

    'testimonials_advanced1' => __('Customize specific styling options for your testimonial.', 'optimizepress'),
    'testimonials_font_settings' => __('Testimonials Styling', 'optimizepress'),

    'text_alignment' => __('Text Alignment', 'optimizepress'),


    'text_block_content' => __('Use the WYSIWYG editor below to add content to your text block.', 'optimizepress'),
    'text_block_font_settings' => __('Select the font size for your main body copy inside the text box. Please note this will not affect headline styles - use the overall', 'optimizepress'),
    'text_block_top_padding' => __('Text Block Top Padding (px)', 'optimizepress'),
    'text_block_bottom_padding' => __('Text Block Bottom Padding (px)', 'optimizepress'),
    'text_block_left_padding' => __('Text Block Left Padding (px)', 'optimizepress'),
    'text_block_right_padding' => __('Text Block Right Padding', 'optimizepress'),
    'text_block_padding_help' => __('Adjust the padding of the inside of your text box (px)', 'optimizepress'),
    'text_block_top_margin' => __('Text Block Top Margin (px)', 'optimizepress'),
    'text_block_top_margin_help' => __('Adjust the margin above your text box (px)', 'optimizepress'),
    'text_block_bottom_margin' => __('Text Block Bottom Margin (px)', 'optimizepress'),
    'text_block_bottom_margin_help' => __('Adjust the margin below your text box (px)', 'optimizepress'),
    'text_block_width' => __('Text Block Width (px)', 'optimizepress'),

    'top_color' => __('Top Color', 'optimizepress'),

    'date' => __('Date', 'optimizepress'),
    'date_format' => __('Date Format', 'optimizepress'),
    'date_format_microcopy' => __('Full list of available options can be found in the <a href="http://php.net/manual/en/function.date.php#refsect1-function.date-parameters" target="_blank">PHP documentation</a>, use a back slash (\) to escape special characters', 'optimizepress'),

    'dynamic_delay_timer' => __('Enter the time when to show your content (in milliseconds)', 'optimizepress'),

    'terms_text' => __('Terms &amp; Conditions Text', 'optimizepress'),
    'accept_text' => __('Accept checkbox label', 'optimizepress'),
    'accept_text_default' => __('I understand and agree to all other Terms and Conditions detailed on this page.', 'optimizepress'),

    'column_text' => __('Column Text', 'optimizepress'),

    'light_or_dark' => __('Light or Dark', 'optimizepress'),

    /* Social Sharing */
    'default_tweet_text' => __('Default Tweet Text', 'optimizepress'),
    'facebook_settings' => __('Facebook Settings', 'optimizepress'),
    'facebook_like_url' => __('URL to Like', 'optimizepress'),
    'button_text' => __('Button Text', 'optimizepress'),
    'twitter_count_url' => __('URL of the page to share', 'optimizepress'),
    'twitter_name' => __('Twitter screen name (enter without "@" sign, if entered, will be added to Tweet as via @screen_name)', 'optimizepress'),
    'twitter_settings' => __('Twitter Settings', 'optimizepress'),
    'google_settings' => __('Google +1 Settings', 'optimizepress'),
    'google_url' => __('URL to +1', 'optimizepress'),
    'pinterest_settings' => __('Pinterest Settings', 'optimizepress'),
    'pinterest_url' => __('URL of the page to pin', 'optimizepress'),
    'pinterest_image_url' => __('URL of the image to pin', 'optimizepress'),
    'pinterest_description' => __('Description of the page to be pinned', 'optimizepress'),
    'share' => __('Share', 'optimizepress'),
    'stumbleupon_settings' => __('StumbleUpon', 'optimizepress'),
    'stumbleupon_url' => __('Page URL (Optional)', 'optimizepress'),
    'linkedin_settings' => __('LinkedIn Settings', 'optimizepress'),
    'social_sharing_background_color' => __('Social Sharing Background Color', 'optimizepress'),

    'navigation_menu' => __('Navigation Menu', 'optimizepress'),
    'navigation_help' => __('Customize your navigation menu using the options below. If you have not yet created a navigation menu, go to <a href="nav-menus.php" target="_blank">Appearance &gt; Menus</a> to create your first menu', 'optimizepress'),

    'payment_gateway' => __('Payment Gateway', 'optimizepress'),
    'membership_level' => __('Membership Level', 'optimizepress'),
    'want_to_charge' => __('I want to charge', 'optimizepress'),
    'one_time' => __('Pick one option', 'optimizepress'),
    'description' => __('Description', 'optimizepress'),
    'packages' => __('Packages'),
    'first' => __('I\'ll offer the first', 'optimizepress'),
    'select' => __('Select:', 'optimizepress'),
    'at' => __('@', 'optimizepress'),
    'one_time_auth' => __('/', 'optimizepress'),
    'one_time_cc' => __('/', 'optimizepress'),
    'one_time' => __('/', 'optimizepress'),
    'currency_cc' => __('Currency', 'optimizepress'),
    'currency_new' => __('Currency', 'optimizepress'),
    'page_style' => __('Paypal Page Style', 'optimizepress'),
    'click_product_type' => __('ClickBank product type', 'optimizepress'),
    'click_product_item' => __('ClickBank product item #', 'optimizepress'),
    'click_skin' => __('ClickBank custom form skin', 'optimizepress'),
    'click_skin_note' => __('Note: Enter custom form skin code to brand your shopping cart', 'optimizepress'),
    'click_fid' => __('PitchPlus Upsell Flow ID', 'optimizepress'),
    'click_fid_recuring' => __('Reccuring Product Type', 'optimizepress'),
    'click_fid_note' => __("Note: Optional ClickBank PitchPlus Upsell Flow ID, which MUST correlate with a PitchPlus Upsell Flow you've configured at ClickBank.com.", "optimizepress"),
    'click_ur' => __('PitchPlus Upsell Flow action', 'optimizepress'),
    'click_ur_note' => __('Note: Optional ClickBank PitchPlus Upsell Flow action (a accept or d decline), which MUST correlate with instructions provided by ClickBank.com for PitchPlus Upsell Flows.', 'optimizepress'),
    'click_f' => __('PitchPlus Upsell Flow session ID', 'optimizepress'),
    'click_f_note' => __('Note: Optional ClickBank PitchPlus Upsell Flow session ID, which MUST correlate with instructions provided by ClickBank.com for PitchPlus Upsell Flows.', 'optimizepress'),
    'one_time_clickbank' => __('Fixed term access', 'optimizepress'),
    'click_trial_period' => __('ClickBank trial period', 'optimizepress'),
    'click_rebill' => __(', then ReBill', 'optimizepress'),

    // Button designer
    'subtext' => __('Subtext', 'optimizepress'),
    'font_properties' => __('Font properties', 'optimizepress'),
    'text_shadow' => __('Text Shadow', 'optimizepress'),
    'vertical_axis' => __('Vertical Axis', 'optimizepress'),
    'horizontal_axis' => __('Horizontal Axis', 'optimizepress'),
    'styling' => __('Styling', 'optimizepress'),
    'border_size' => __('Border Size', 'optimizepress'),
    'border_radius' => __('Border Radius', 'optimizepress'),
    'border_color' => __('Border Color', 'optimizepress'),
    'border_opacity' => __('Border Opacity', 'optimizepress'),
    'border_weight' => __('Border Thickness/Weight', 'optimizepress'),
    'gradient' => __('Gradient', 'optimizepress'),
    'shine' => __('Shine', 'optimizepress'),
    'drop_shadow' => __('Drop Shadow', 'optimizepress'),
    'spread_radius' => __('Spread Radius', 'optimizepress'),
    'shadow_color' => __('Shadow Color', 'optimizepress'),
    'opacity' => __('Opacity', 'optimizepress'),
    'inner_shadow' => __('Inner Shadow', 'optimizepress'),
    'blur_radius' => __('Blur Radius', 'optimizepress'),
    'save_preset' => __('Save Preset', 'optimizepress'),
    'delete_preset' => __('Delete Preset', 'optimizepress'),
    'letter_spacing' => __('Letter Spacing', 'optimizepress'),

    //Membership order button
    'no_options_for_this_slide' => __('Default Payment Gateway button will be used. No options for customization', 'optimizepress'),

    //Membership sidebars
    'membership_sidebar_product' => __('Product', 'optimizepress'),
    'membership_sidebar_category' => __('Category', 'optimizepress'),
    'membership_sidebar_subcategory' => __('Subcategory', 'optimizepress'),
    'membership_sidebar_show_children' => __('List pages from page parent product', 'optimizepress'),
    'membership_sidebar_same_level' => __('Show pages from this page level only', 'optimizepress'),
    'membership_sidebar_title_styling' => __('Title styling', 'optimizepress'),
    'membership_sidebar_content_styling' => __('Content styling', 'optimizepress'),

    // Javascript element
    'javascript_content' => __('Enter custom JavaScript (Please ensure you do not include any calls to external jQuery libraries as this may break your page!)', 'optimizepress'),
    'javascript_description' => __('WARNING: Be careful when entering JavaScript to your page. It should be valid, or it will break your page.', 'optimizepress'),


    // Membership page listing element
    'membership_page_listings_columns' => __('Number of columns', 'optimizepress'),
    'show_comments' => __('Show comments', 'optimizepress'),
    'show_drip_content' => __('Show drip delay timer (Content will only show for this option if you do not have hide protected content activated)', 'optimizepress'),
    'page_listings_content_styling' => __('Page listings content styling', 'optimizepress'),
    'page_listings_title_styling' => __('Page listings title styling', 'optimizepress'),
    'page_listings_resize_thumb_height' => __('Resize thumbnail height? (Use this option if you are using icons for your thumbnails - ensure all icons are the same height)', 'optimizepress'),
    'page_listings_show_children' => __('Show Page Children only - this will list any pages directly under this page in your page heirarchy.', 'optimizepress'),
    'page_listings_sort_order' => __('Order pages', 'optimizepress'),
    'hide_description' => __('Hide description', 'optimizepress'),

    //Membership login form
    'public_title' => __('Public title', 'optimizepress'),
    'when_not_logged_in' => __('(when not logged in)', 'optimizepress'),
    'redirection_after_login' => __('Redirection after login', 'optimizepress'),
    'signup_now' => __('Signup now', 'optimizepress'),
    'enter_url_or_use_automatic' => __('(enter URL, or just use <code>%%automatic%%</code>, leave blank to exclude this link)', 'optimizepress'),
    'additional_xhtml_php_code' => __('Additional XHTML/PHP code?', 'optimizepress'),
    'profile_title' => __('Profile title', 'optimizepress'),
    'when_logged_in' => __('(when logged in)', 'optimizepress'),
    'display_gravatar_image' => __('Display gravatar image?', 'optimizepress'),
    'link_to_gravatar' => __('Link to gravatar.com?', 'optimizepress'),
    'display_user_name' => __("Display user's name?", "optimizepress"),
    'my_account' => __('My account', 'optimizepress'),
    'edit_profile' => __('Edit profile', 'optimizepress'),
    'redirection_after_logout' => __('Redirection after logout', 'optimizepress'),
    'login_welcome_page' => __('Login welcome page', 'optimizepress'),
    'login_screen' => __('Login screen', 'optimizepress'),
    'previous_page' => __('Previous page', 'optimizepress'),
    'home_page' => __('Home page', 'optimizepress'),
    'yes_display_gravatar' => __('Yes, display Gravatar', 'optimizepress'),
    'no_do_not_display' => __('No, do NOT display', 'optimizepress'),
    'no_do_not_apply' => __('No, do NOT apply', 'optimizepress'),
    'yes_apply_link' => __('Yes, apply link', 'optimizepress'),
    'yes_display_user_name' => __("Yes, display User's name", "optimizepress"),

    // Optin box
    'integration_type' => __('Integration Type', 'optimizepress'),
    'provider_list' => __('Provider List', 'optimizepress'),
    'thank_you_page_url' => __('Thank You Page URL', 'optimizepress'),
    'already_subscribed_url' => __('User Already Subscribed Page URL', 'optimizepress'),
    'text_below_button' => __('Textual Link Below Button', 'optimizepress'),
    'gotowebinar' => __('GoToWebinar', 'optimizepress'),
    'gotowebinar_list' => __('GoToWebinar Webinar', 'optimizepress'),
    'ems_loading_time' => __('Note: Lists can take up to 1 minute to be retrieved from your provider', 'optimizepress'),
    'activecampaign_desc' => __('Enter the form ID from ActiveCampaign if you wish to use the Opt-in confirmation email settings you have created inside the settings for this form.', 'optimizepress'),
    'double_optin' => __('Double Optin', 'optimizepress'),
    'welcome_email' => __('Send Welcome Email', 'optimizepress'),
    'signup_form_id' => __('Subscription Form ID', 'optimizepress'),
    'no_extra_fields_for_selected_style' => __('This Optin Box design does not support additional fields', 'optimizepress'),
    'email_ems_auto_required' => __('We automatically integrate with the email field from your Email Marketing Service. If you have created a web form for integration, please ensure it includes an email field.', 'optimizepress'),

    // Images Asset
    'asset_images_custom_width' => __('Custom Image Width?', 'optimizepress'),

    // Languages
    'english' => __('English', 'optimizepress'),
    'french' => __('French', 'optimizepress'),
    'spanish' => __('Spanish', 'optimizepress'),
    'russian' => __('Russian', 'optimizepress'),
    'german' => __('German', 'optimizepress'),
    'italian' => __('Italian', 'optimizepress'),
    'portugese' => __('Portugese', 'optimizepress'),
    'romanian' => __('Romanian', 'optimizepress'),
    'turkish' => __('Turkish', 'optimizepress'),
    'japanese' => __('Japanese', 'optimizepress'),
    'indonesian' => __('Indonesian', 'optimizepress'),
    'malay' => __('Malay', 'optimizepress'),
    'korean' => __('Korean', 'optimizepress'),
    'swedish' => __('Swedish', 'optimizepress'),
    'czech' => __('Czech', 'optimizepress'),
    'dutch' => __('Dutch', 'optimizepress'),
    'polish' => __('Polish', 'optimizepress'),
    'norwegian' => __('Norwegian', 'optimizepress'),
    'danish' => __('Danish', 'optimizepress'),

    // Live Search
    'live_search_product' => __('Product', 'optimizepress'),
    'live_search_category' => __('Category', 'optimizepress'),
    'live_search_subcategory' => __('Subcategory', 'optimizepress'),
    'live_search_all_pages' => __('Search within all pages', 'optimizepress'),
    'live_search_placeholder' => __('Search box text', 'optimizepress'),

    // file download
    'select_level' => __('Membership level', 'optimizepress'),
    'select_packages' => __('Membership packages', 'optimizepress'),
    'file_name' => __('File name', 'optimizepress'),
    'file_description' => __('File description', 'optimizepress'),
    'file' => __('File', 'optimizepress'),


    // custom_html
    'custom_html_description' => __('WARNING: Be careful when adding custom HTML. It should be valid HTML or it could break your page. EVS embed code is not compatible with our OverlayOptimizer element.', 'optimizepress'),

    // membership order button
    'currency' => __('Currency', 'optimizepress'),
    'success_url' => __('Success URL', 'optimizepress'),

    // Popup / OverlayOptimizer
    'popup_width' => __("Window width (px). <br />If you enter 0 or leave this field empty, OverlayOptimizer window will be sized according to it's content size."),
    'popup_button' => __('OverlayOptimizer Button', 'optimizepress'),
    'popup_container' => __('OverlayOptimizer Window', 'optimizepress'),
    'open_effect' => __('Open effect', 'optimizepress'),
    'close_effect' => __('Close effect', 'optimizepress'),
    'open_speed' => __('Open speed', 'optimizepress'),
    'close_speed' => __('Close speed', 'optimizepress'),
    'overlay_pop' => __('Overlay Pop', 'optimizepress'),
    'overlay_pop_info' => __('If you wish to use your OverlayOptimizer as an exit popup or delayed popup, use the options below. Please note the popup functionality has a built in 10-second repeat-trigger delay so cannot be triggered twice within 10 seconds. This is to ensure a positive user experience for your site visitors.', 'optimizepress'),
    'overlay_pop_exit_intent' => __('<strong>Exit Intent</strong> <br /> Open the OverlayOptimizer element when user moves their cursor outside the main browser window', 'optimizepress'),
    'overlay_pop_trigger_time' => __('<strong>Open the OverlayOptimizer element after certain number of seconds (seconds)</strong><br />0 = Don\'t trigger the popup (will still trigger for Exit Intent if switched on above)<br />', 'optimizepress'),
    'overlay_pop_trigger_dontshow' => __('<strong>Don\'t open the OverlayOptimizer for a certain number of days after first open (days)</strong><br />0 = Open the OverlayOptimizer every time (This will be reset if user clears cookies or changes browser)', 'optimizepress'),
    'overlay_pop_dont_show_on_mobile' => __('<strong>Hide on Mobile</strong><br />Don\'t open OverlayOptimizer on mobile devices (screens smaller than 767px wide).', 'optimizepress'),
    'overlay_pop_dont_show_on_tablet' => __('<strong>Hide on Tablet</strong><br />Don\'t open OverlayOptimizer on tablet devices (screens smaller than 959px wide).', 'optimizepress'),

    // OptimizeLeads
    'optimizeleads_description' => __('<strong>OptimizeLeads</strong> Boxes are retrieved directly from OptimizeLeads. If you want to change anything on one of the boxes, please login into OptimizeLeads, and change it there; the changes will be reflected here.'),
    'optimizeleads_embed_code' => __("OptimizeLeads Embed Code"),
    'optimizeleads_embed_code_loading' => __("Loading Embed Code..."),
    'optimizeleads_embed_code_description' => __("Embed code will be automatically retrieved from OptimizeLeads and inserted into your page. You don't have to copy it or do anything with it manually."),
    'optimizeleads_no_api_key' => __("You haven't inserted an API key for OptimizeLeads. Please open OptimizePress Dashboard, and under section OptimizeLeads enter your API key to use this element.<br /><br /> You can find or create an OptimizeLeads API Key on OptimizeLeads Integrations page, under <a href='https://my.optimizeleads.com/api-keys' target='blank'>API Keys</a> section."),
    'optimizeleads_invalid_api_key' => __("Your OptimizeLeads API key appears to be invalid. Please open OptimizePress Dashboard, and under section OptimizeLeads enter your correct API key to use this element.<br /><br /> You can find or create an OptimizeLeads API Key on OptimizeLeads Integrations page, under <a href='https://my.optimizeleads.com/api-keys' target='blank'>API Keys</a> section."),
    'optimizeleads_no_boxes' => __("You don't have any boxes ready for publishing in OptimizeLeads. Please log into your <a href='http://my.optimizeleads.com/' target='blank'>OptimizeLeads</a> account, create a box, connect it to an integration, and it will appear here."),
);

$arr = apply_filters('op_assets_lang_list', $arr);
